version: "3"
services:   
    mysql:
        container_name : gunma_mysql
        image: mysql:8.0
        ports:
            - "3306:3306"
        environment: 
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        volumes:
            - mysql_volume:/etc/mysql/conf.d
        networks:
            - gunma-net
    backend:
        image: dhanifajar15/gunma-backend:0.1.0
        container_name : gunma_backend
        build:
            context: ./
            dockerfile: ./docker/images/nginx/Dockerfile
        links:
            - mysql
        ports: 
            - "8080:80"
        networks:
            - gunma-net
volumes:
   mysql_volume:

networks:
   gunma-net: