version: "3"
services: 
    web_server:
        build: docker/images/nginx
        command: nginx -g "daemon off;"
        links:
            - php
        ports: 
            - "80:80"
            - "443:443"
        volumes: 
            - ./public:/var/www/html/app/public
            
    php:
        build: docker/images/php
        volumes: 
            - ./:/var/www/html/app
        working_dir: /var/www/html/app
        links:
            - mysql
        ports: 
            - "9000:9000"
        environment: 
            APP_ENV: local
            APP_DEBUG: 'true'
            APP_KEY: ${APP_KEY}
            APP_LOCALE: en
            APP_FALLBACK_LOCALE: en
            DB_CONNECTION: mysql
            DB_HOST: mysql
            DB_DATABASE: ${DB_DATABASE}
            DB_USERNAME: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}

    mysql:
        image: mysql:8.0
        ports:
            - "3306:3306"
        environment: 
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        volumes:
            - mysql_data:/etc/mysql/conf.d

    phpmyadmin:
        image: phpmyadmin:latest
        ports:
            - 8080:80
        links:
            - mysql
        environment:
            PMA_HOST: mysql
            PMA_PASSWORD: ${DB_PASSWORD}
        restart: unless-stopped

volumes:
    mysql_data:
        external: true